# Generated by Django 3.1.6 on 2021-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='desc',
            field=models.CharField(default='SOME STRING', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
