# Generated by Django 3.1.6 on 2021-02-20 18:44

from django.db import migrations, models
import main_gusto.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0004_auto_20210220_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('photo', models.ImageField(upload_to=main_gusto.models.Chef.get_file_name)),
                ('desc', models.CharField(default='SOME STRING', max_length=200, unique=True)),
            ],
        ),
    ]
