# Generated by Django 3.1.6 on 2021-02-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0006_address_cafeinfo_massage_openinghours_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
