# Generated by Django 3.1.6 on 2021-02-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0007_auto_20210225_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_massage',
            new_name='user_message',
        ),
    ]
